//categories
export const GET_CATEGORIES = 'GET_CATEGORIES';

//comment
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const VOTE_SINGLE_COMMENT = "VOTE_SINGLE_COMMENT";
export const ADD_COMMENT_ON_POST = "ADD_COMMENT_ON_POST";
export const DELETE_COMMENT_FROM_POST = "DELETE_COMMENT_FROM_POST";
export const GET_SINGLE_COMMENT  = "GET_SINGLE_COMMENT";
export const UPDATE_SINGLE_COMMENT = "UPDATE_SINGLE_COMMENT";

//posts
export const RETRIEVE_POSTS         = 'RETRIEVE_POSTS';
export const GET_POSTS_BY_CATEGORY  = 'GET_POSTS_BY_CATEGORY';
export const ADDING_POSTS           = 'ADDING_POSTS';
export const VOT_ON_POST            = 'VOT_ON_POST';
export const DELETE_SINGLE_POST     = 'DELETE_SINGLE_POST';
export const UPDATE_POST            = 'UPDATE_POST';
export const GET_POST_DETAILS       = 'GET_POST_DETAILS';
export const GET_SINGLE_POST_DETAILS = 'GET_SINGLE_POST_DETAILS';