//categories
export const GET_CATEGORIES = 'GET_CATEGORIES';

//comment
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const VOTE_SINGLE_COMMENT = "VOTE_SINGLE_COMMENT";
export const ADD_COMMENT_ON_POST = "ADD_COMMENT_ON_POST";
export const DELETE_COMMENT_FROM_POST = "DELETE_COMMENT_FROM_POST";
export const GET_SINGLE_COMMENT  = "GET_SINGLE_COMMENT";
export const UPDATE_SINGLE_COMMENT = "UPDATE_SINGLE_COMMENT";